// <auto-generated />
using System;
using CineX_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CineX_API.Data.Migrations
{
    [DbContext(typeof(CineXDbContext))]
    [Migration("20260619161400_AddProjectFieldsAndActStatus")]
    partial class AddProjectFieldsAndActStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CineX_API.Models.Act", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Acts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectId = 1,
                            SequenceOrder = 1,
                            Status = "DONE",
                            Summary = "Thám tử Lâm nhận vụ án đầu tiên",
                            Title = "Hồi I - Khởi đầu"
                        },
                        new
                        {
                            Id = 2,
                            ProjectId = 1,
                            SequenceOrder = 2,
                            Status = "IN_PROGRESS",
                            Summary = "Lâm và Linh bắt đầu điều tra",
                            Title = "Hồi II - Điều tra"
                        },
                        new
                        {
                            Id = 3,
                            ProjectId = 1,
                            SequenceOrder = 3,
                            Status = "WAITING",
                            Summary = "Manh mối dẫn đến nguy hiểm",
                            Title = "Hồi III - Nguy hiểm"
                        },
                        new
                        {
                            Id = 4,
                            ProjectId = 1,
                            SequenceOrder = 4,
                            Status = "WAITING",
                            Summary = "Sự thật được phơi bày",
                            Title = "Hồi IV - Kết cục"
                        },
                        new
                        {
                            Id = 5,
                            ProjectId = 2,
                            SequenceOrder = 1,
                            Status = "DONE",
                            Summary = "Những người bạn gặp lại nhau",
                            Title = "Hồi I - Gặp gỡ"
                        },
                        new
                        {
                            Id = 6,
                            ProjectId = 2,
                            SequenceOrder = 2,
                            Status = "IN_PROGRESS",
                            Summary = "Các mối quan hệ bắt đầu rạn nứt",
                            Title = "Hồi II - Mâu thuẫn"
                        },
                        new
                        {
                            Id = 7,
                            ProjectId = 2,
                            SequenceOrder = 3,
                            Status = "WAITING",
                            Summary = "Tìm lại tình bạn",
                            Title = "Hồi III - Hòa giải"
                        },
                        new
                        {
                            Id = 8,
                            ProjectId = 3,
                            SequenceOrder = 1,
                            Status = "DONE",
                            Summary = "Gia đình chuyển vào ngôi nhà cũ",
                            Title = "Hồi I - Chuyển đến"
                        },
                        new
                        {
                            Id = 9,
                            ProjectId = 3,
                            SequenceOrder = 2,
                            Status = "DONE",
                            Summary = "Những sự kiện kỳ lạ xảy ra",
                            Title = "Hồi II - Bí ẩn"
                        },
                        new
                        {
                            Id = 10,
                            ProjectId = 3,
                            SequenceOrder = 3,
                            Status = "IN_PROGRESS",
                            Summary = "Đối mặt với bí mật ngôi nhà",
                            Title = "Hồi III - Đối mặt"
                        });
                });

            modelBuilder.Entity("CineX_API.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorName")
                        .HasColumnType("text");

                    b.Property<string>("CastingStatus")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CastingStatus = "APPROVED",
                            Description = "Thám tử Nam, cứng rắn và tận tâm với công việc",
                            Name = "Lâm",
                            Role = "MAIN"
                        },
                        new
                        {
                            Id = 2,
                            CastingStatus = "APPROVED",
                            Description = "Nữ luật sư tài ba, quyết đoán",
                            Name = "Linh",
                            Role = "MAIN"
                        },
                        new
                        {
                            Id = 3,
                            CastingStatus = "PENDING",
                            Description = "Đồng sự của Lâm",
                            Name = "Minh",
                            Role = "SUPPORT"
                        });
                });

            modelBuilder.Entity("CineX_API.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Setting")
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nhà Hát Lớn",
                            Notes = "Cần đèn chiếu sáng chuyên nghiệp, có âm thanh surround",
                            Setting = "INT",
                            Time = "NIGHT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Phố Cũ Hàng Nón",
                            Notes = "Quay vào buổi sáng, tránh đám đông",
                            Setting = "EXT",
                            Time = "DAY"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nhà Máy Khai Thác",
                            Notes = "Cấu trúc bê tông bị phá hủy, yêu cầu an toàn cao",
                            Setting = "INT",
                            Time = "NIGHT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Quán Cà Phê Vỉa Hè",
                            Notes = "Bàn ghế gỗ cũ, không quá sáng",
                            Setting = "EXT",
                            Time = "DAY"
                        });
                });

            modelBuilder.Entity("CineX_API.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CrewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Director")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Genre")
                        .HasColumnType("text");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text");

                    b.Property<double>("Progress")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CrewCount = 45,
                            Description = "Câu chuyện về một thám tử tìm kiếm sự thật giữa những bóng tối của thành phố.",
                            Director = "Nguyễn A",
                            EndDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Genre = "Tâm lý - Tội phạm",
                            PosterUrl = "https://via.placeholder.com/300x450/FF4D00/FFFFFF?text=Project+1",
                            Progress = 0.65000000000000002,
                            StartDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "SHOOTING",
                            Title = "Ánh Sáng Thành Phố"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CrewCount = 38,
                            Description = "Một bộ phim về tình bạn, tình yêu và những lựa chọn cuộc đời.",
                            Director = "Trần B",
                            EndDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Genre = "Drama",
                            PosterUrl = "https://via.placeholder.com/300x450/4C6EF5/FFFFFF?text=Project+2",
                            Progress = 0.40000000000000002,
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "SHOOTING",
                            Title = "Mưa Hè"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CrewCount = 32,
                            Description = "Một bộ phim kinh dị về những bí mật ẩn giấu trong ngôi nhà cũ.",
                            Director = "Lê C",
                            EndDate = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Genre = "Kinh dị",
                            PosterUrl = "https://via.placeholder.com/300x450/51CF66/FFFFFF?text=Project+3",
                            Progress = 0.84999999999999998,
                            StartDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "POST_PRODUCTION",
                            Title = "Quái Vật Đêm"
                        });
                });

            modelBuilder.Entity("CineX_API.Models.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActId")
                        .HasColumnType("integer");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("SceneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Setting")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.HasIndex("LocationId");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("CineX_API.Models.SceneCharacter", b =>
                {
                    b.Property<int>("SceneId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.HasKey("SceneId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("SceneCharacters");
                });

            modelBuilder.Entity("CineX_API.Models.Act", b =>
                {
                    b.HasOne("CineX_API.Models.Project", "Project")
                        .WithMany("Acts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CineX_API.Models.Scene", b =>
                {
                    b.HasOne("CineX_API.Models.Act", "Act")
                        .WithMany("Scenes")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineX_API.Models.Location", "Location")
                        .WithMany("Scenes")
                        .HasForeignKey("LocationId");

                    b.Navigation("Act");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CineX_API.Models.SceneCharacter", b =>
                {
                    b.HasOne("CineX_API.Models.Character", "Character")
                        .WithMany("SceneCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineX_API.Models.Scene", "Scene")
                        .WithMany("SceneCharacters")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("CineX_API.Models.Act", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("CineX_API.Models.Character", b =>
                {
                    b.Navigation("SceneCharacters");
                });

            modelBuilder.Entity("CineX_API.Models.Location", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("CineX_API.Models.Project", b =>
                {
                    b.Navigation("Acts");
                });

            modelBuilder.Entity("CineX_API.Models.Scene", b =>
                {
                    b.Navigation("SceneCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
